import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My NEXT JS APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li className='text-center text-red-500 font-bold'>
              <Link href="/about" />
            </li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  )
}
